MY_SOURCES = main.c read-file.c

C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Werror

CUR_DIR = $(shell pwd)

my_rule: sub_rule
	echo I will compiles my sources $(MY_SOURCES)

my_rule: sub_rule
	echo This is my rule, in $(CUR_DIR)